version: "3"

services:
  back_end:
    image: "{{ back_end_docker_image }}:{{ back_end_docker_tag }}"
    ports:
      - "{{ back_end_port }}:3000"
    environment:
      MONGO_URI: "mongodb://{{ database_uri }}:{{ database_port }}/madu?authSource=admin"